### ISSUE TITLE
Validation without creating new properties?

### ISSUE THREAD

**Issue by thatside-zaraffa** [mokkabonna/vue-vuelidate-jsonschema#14]
IMO it could be useful to have JSON Schema validation on predefined set of fields exposed as `data` without creating new ones based on `schema` field. 
This approach would allow using JSON Schema as validation-only tool for projects which do not require dynamically created forms and components and for those who prefer explicitly declared data properties.

**Comment by thatside-zaraffa** [comment]
It seems it works well using following snippet:
```
schema: [
      {
        mountPoint: 'register',
        schema: fetchSchema('register'),
      }],
    data() {
      return {
        register: {
          email: '',
          password: '',
          passwordRepeat: '',
          termsConfirmed: false,
        },
      };
    },
```
  BTW fetchSchema is my custom function - this isn't described so clear.

**Comment by mokkabonna** [comment]
Yes the data generated is merged with standard vue mixin merge strategy. Meaning your own data is prioritized.

**Comment by thatside-zaraffa** [comment]
Thank you for your response! I've tried this once earlier and it wasn't working but I think I made something wrong.
